(dp1
S'output'
p2
S"<type 'exceptions.AttributeError'> "
p3
sS'layer'
p4
S'/home/abdulhalim/Desktop/web2py/applications/motor/controllers/default.py'
p5
sS'code'
p6
S'<code object <module> at 0x7f8af425a0b0, file "/home/abdulhalim/Desktop/web2py/applications/motor/controllers/default.py", line 1>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/abdulhalim/Desktop/web2py/gluon/restricted.py", line 219, in restricted\n    exec(ccode, environment)\n  File "/home/abdulhalim/Desktop/web2py/applications/motor/controllers/default.py", line 65, in <module>\n  File "/home/abdulhalim/Desktop/web2py/gluon/globals.py", line 409, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/abdulhalim/Desktop/web2py/gluon/tools.py", line 3964, in f\n    return action(*a, **b)\n  File "/home/abdulhalim/Desktop/web2py/applications/motor/controllers/default.py", line 21, in add_device\n    user_ref_id = db.executesql("SELECT id FROM auth_user WHERE username=%s", auth.user)\n  File "/home/abdulhalim/Desktop/web2py/gluon/packages/dal/pydal/base.py", line 767, in executesql\n    adapter.execute(query, placeholders)\n  File "/home/abdulhalim/Desktop/web2py/gluon/packages/dal/pydal/adapters/__init__.py", line 67, in wrap\n    return f(*args, **kwargs)\n  File "/home/abdulhalim/Desktop/web2py/gluon/packages/dal/pydal/adapters/base.py", line 410, in execute\n    rv = self.cursor.execute(command, *args[1:], **kwargs)\n  File "/home/abdulhalim/Desktop/web2py/gluon/contrib/pymysql/cursors.py", line 164, in execute\n    query = self.mogrify(query, args)\n  File "/home/abdulhalim/Desktop/web2py/gluon/contrib/pymysql/cursors.py", line 143, in mogrify\n    query = query % self._escape_args(args, conn)\n  File "/home/abdulhalim/Desktop/web2py/gluon/contrib/pymysql/cursors.py", line 129, in _escape_args\n    return conn.escape(args)\n  File "/home/abdulhalim/Desktop/web2py/gluon/contrib/pymysql/connections.py", line 793, in escape\n    return escape_item(obj, self.charset, mapping=mapping)\n  File "/home/abdulhalim/Desktop/web2py/gluon/contrib/pymysql/converters.py", line 27, in escape_item\n    val = encoder(val, mapping)\n  File "/home/abdulhalim/Desktop/web2py/gluon/contrib/pymysql/converters.py", line 110, in escape_unicode\n    return u"\'%s\'" % _escape_unicode(value)\n  File "/home/abdulhalim/Desktop/web2py/gluon/contrib/pymysql/converters.py", line 73, in _escape_unicode\n    return value.translate(_escape_table)\n  File "/home/abdulhalim/Desktop/web2py/gluon/packages/dal/pydal/objects.py", line 99, in __getattr__\n    raise AttributeError\nAttributeError\n'
p11
s.