(dp1
S'output'
p2
S"<type 'exceptions.UnboundLocalError'> local variable 'user_name' referenced before assignment"
p3
sS'layer'
p4
S'/home/abdulhalim/Desktop/web2py/applications/motor/controllers/default.py'
p5
sS'code'
p6
S'<code object <module> at 0x7fe2523ed130, file "/home/abdulhalim/Desktop/web2py/applications/motor/controllers/default.py", line 1>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/abdulhalim/Desktop/web2py/gluon/restricted.py", line 219, in restricted\n    exec(ccode, environment)\n  File "/home/abdulhalim/Desktop/web2py/applications/motor/controllers/default.py", line 53, in <module>\n  File "/home/abdulhalim/Desktop/web2py/gluon/globals.py", line 409, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/abdulhalim/Desktop/web2py/gluon/tools.py", line 3964, in f\n    return action(*a, **b)\n  File "/home/abdulhalim/Desktop/web2py/applications/motor/controllers/default.py", line 14, in add_device\n    return dict(user=user_name, device_name=device_name, device_id=device_id,device_loc=device_loc, device_model=device_model)\nUnboundLocalError: local variable \'user_name\' referenced before assignment\n'
p11
s.